export const INCOME_LOADING = 'INCOME_LOADING';
export const ADD_INCOMES = 'ADD_INCOMES';
export const INCOME_FAILED = 'INCOME_FAILED';
export const UPDATE_INCOME = 'UPDATE_INCOME';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';